openapi: 3.1.0
x-stoplight:
  id: go09amaf0562i
info:
  title: Blog
  version: "1.0"
  description: ""
servers:
  - url: "http://localhost:3000"
paths:
  /blogs:
    parameters: []
    get:
      summary: ""
      operationId: get-blogs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    body:
                      type: string
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      description: ""
  "/blogs/{blogId}":
    parameters:
      - schema:
          type: number
        name: blogId
        in: path
        required: true
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  body:
                    type: string
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      operationId: ""
      description: ""
    post:
      summary: ""
      operationId: post-blogs-blogId
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  body:
                    type: string
        "400":
          description: Not Found
        "500":
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              minProperties: 0
              properties:
                title:
                  type: string
                body:
                  type: string
      description: ブログ作成
    patch:
      summary: ""
      operationId: patch-blogs-blogId
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  body:
                    type: string
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      description: ブログ更新
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                title:
                  type: string
                body:
                  type: string
        description: ""
components:
  schemas:
    Blog:
      title: Blog
      type: object
      examples:
        - id: 1
          title: 初登校
          body: 内容は考え中
          created_at: "2022-08-24"
          updated_at: "2022-08-24"
      description: ブログ
      x-internal: false
      x-stoplight:
        id: 110d4c89bb272
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        title:
          type: string
        body:
          type: string
        createdAt:
          type: string
          format: date
          description: The date that the user was created.
        updatedAt:
          type: string
          format: date
          example: "1997-10-31"
      required:
        - id
        - title
        - body
        - createdAt
        - updatedAt
  securitySchemes: {}
x-internal: false
